### PR TITLE
Manually implement IAccessible

### PR DESCRIPTION
**Pull request by wjk**
IAccessible is a very strange interface. It defines property getters and setters that take arguments, which are represented in C# by `get_*` and `set_*` methods. The source generator cannot handle this syntax correctly, even if modified to recognize property get/set methods with arguments. With this change applied, the test app builds and runs without any problems after NativeAOT. I have not verified that the interface properly provides automation information to the system, because I do not know how to do so.

### CODE REVIEW

**Comment by wjk** [comment]
@kant2002 Once this and #10 are merged, could you do me a solid and cut a new release to NuGet.org? I would like to use this library in my personal projects now that the bugs I have found have been squashed. Thanks!

**Comment by kant2002** [comment]
I would like to have VARIANT marshalling implemented differently and preferably in codegen. As you notice I did not implement get/set pattern properly, so that's another problem which I have plans to implement.

I can cut release with these changes, but after I introduce these changes you may need to re-test application.
If you tell me a bit more about scenario where you need IAccessibility, I'm gladly test on them to be a bit more pro-active with potential problems.

**Comment by kant2002** [comment]
Also important detail for me, do you target .NET 5.0 or .NET 6.0 (if so, is it preview or nighlty?)

**Comment by wjk** [comment]
@kant2002 Honestly, I implemented IAccessible simply because I thought I could. If you would prefer to close this PR, no skin off my back. (Also, what would you want to do differently about VARIANT marshaling? The technique I chose seems to be the simplest way to do so.) Finally, I target both .NET 5 and .NET 6 (and I use only the official preview builds of the latter). I am trying to migrate all my projects from .NET 5 to .NET 6, but it’s a slow and gradual process. Thanks!

**Comment by kant2002** [comment]
I would start with creation of test in similar spirit as `StringParameter`. https://github.com/kant2002/WinFormsComInterop/blob/fdf3958e7e418f6b0d88d81b3446efcfde95c376/WinFormsComInterop.SourceGenerator.Tests/RuntimeCallableWrapperTest.cs#L1072

with difference approximately like that
```
System.Variant local_1;
Marshal.GetNativeVariantForObject(dwOrigin, (System.IntPtr)&local_1);
result = ((delegate* unmanaged<System.IntPtr, long, System.IntPtr, ulong*, int>)vtbl[3])(thisPtr, dlibMove, &local_1, plibNewPosition);
```

System.Variant is most likely for me temporary solution, because I definitely need class which is not so tightly coupled with built-in COM in .NET and Variant marshalling required that I codegen support library in the project, since built-in VARIANT marshalling a bit tricky. I would again consult with previous implementation which I done here https://github.com/dotnet/runtimelab/pull/1142/files and try to get as much as possible from there. On introspection, maybe System.Variant would be good.

Then I have to declare class which implement that kind of marshalling. VariantMarshaller let's say. I would start with empty derived class from Marshaller and add methods as nescessary.

Look for https://github.com/dotnet/runtimelab/blob/feature/DllImportGenerator/designs/Pipeline.md#stub-code-generation for approximate design of marshalling. I use different naming, but thinks that's most complete way how marshalling structured.

I want split net5.0 and net6.0 targeting of WinFormsComInterop since I can limit amount of supported interfaces, System.Drawing now works without my library in .NET 6 Preview 7. I can postpone that split for now.

**Comment by kant2002** [comment]
@wjk in addition to previous comment. If you don't need your changes directly in your apps, I can release as is, so you can use latest verison.

**Comment by wjk** [comment]
@kant2002 I am OK with releasing both NuGet packages as-is, without the changes in this PR. As I said, this was a very low-priority change. Thanks!

**Pull request closed without merging**
